version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - dev.env
    image: postgres
    environment:
      - POSTGRES_USER=start_admin
      - POSTGRES_PASSWORD=start_password
      - POSTGRES_DB=start_db
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 8030:8080

volumes:
  db:
